version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    networks:
      - net

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net

  # streamlit-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.streamlit
  #   container_name: streamlit-app
  #   restart: always
  #   depends_on:
  #     - fastapi-app
  #   ports:
  #     - "8501:8501"
  #   volumes:
  #     - .:/app
  #   environment:
  #     FASTAPI_URL: "http://fastapi-app:8000"
  #   networks:
  #     - net

volumes:
  postgres_data:

networks:
  net:
    driver: bridge